import { AbstractBaseEntity, SystemFileDTO } from '@mt-framework-ng/core';
import { TransferInfoDTO } from './TransferInfoDTO';

/**
 * Generated By SmartSwagger DTO
 * @Author chenzhongde
 * @Date 2021/11/4
 */
export interface TransferDisposeDTO extends AbstractBaseEntity {
  /**
   * undefined
   */
  sendLetterTime?: string;

  /**
   * 是否发函
   */
  isSendLetter?: boolean;

  /**
   * 是否处分
   */
  isPunish?: boolean;

  /**
   * 处分日期
   */
  punishTime?: string;

  /**
   * 处理描述
   */
  transferDescription?: string;

  /**
   * 移交信息
   */
  transferInfo?: TransferInfoDTO;

  /**
   * 关联附件集合
   */
  attachFiles?: Array<SystemFileDTO>;

  /**
   * 移交信息id
   */
  transferInfoId?: string;

  /**
   * 关联附件编码集合
   */
  attachFileIds?: Array<string>;
}
