import { AbstractBaseEntity } from '@mt-framework-ng/core';
import { TransferDisposeDTO } from './TransferDisposeDTO';

/**
 * Generated By SmartSwagger DTO
 * @Author chenzhongde
 * @Date 2021/11/4
 */
export interface TransferRecordDTO extends AbstractBaseEntity {
  /**
   * 一级处分类型
   */
  mainPunishType?: string;

  /**
   * 处分类型
   */
  punishType?: string;

  /**
   * 处分人数
   */
  punishNumberPeople?: number;

  /**
   * 移交处理
   */
  transferDispose?: TransferDisposeDTO;
}
