import { AbstractBaseEntity, SystemFileDTO } from '@mt-framework-ng/core';
import { UserDTO } from '@ng-mt-framework/api';
import { RectifyProblemDTO } from './rectify-problem-dto';

/**
 * Generated By SmartSwagger DTO
 * @Author chenzhongde
 * @Date 2021/11/4
 */
export interface TransferInfoDTO extends AbstractBaseEntity {
  /**
   * 名称
   */
  name?: string;

  /**
   * 移交原因
   */
  transferCause?: string;

  /**
   * 移交处理状态
   */
  transferDisposeStatus?: string;

  /**
   * 是否审计部门移交部门： true ?: 审计部  false ?: 整改部门(市医只提供审计部门移交)
   */
  isAudit?: boolean;

  /**
   * 是否发函
   */
  isSendLetter?: boolean;

  /**
   * 是否处分
   */
  isPunish?: boolean;

  /**
   * 处理结果
   */
  processingResults?: string;

  /**
   * 关联整改问题
   */
  rectifyProblem?: RectifyProblemDTO;

  /**
   * 关联移交问题负责人
   */
  handler?: UserDTO;

  /**
   * 关联文件
   */
  attachFiles?: Array<SystemFileDTO>;

  /**
   * 关联整改问题ID
   */
  rectifyProblemId?: string;

  /**
   * 关联移交问题负责人ID
   */
  handlerId?: string;

  /**
   * 关联附件集合编码
   */
  attachFileIds?: Array<string>;
}
