/**
 * Generated By SmartSwagger DTO
 * @Author chenzhongde
 * @Date 2021/10/13
 */
export interface ChangeMsOrRp {
  /**
   * 整改措施状态
   */
  measureStatus?: string;

  /**
   * 整改措施进度
   */
  rectifyProgress?: number;
}
