import { AbstractBaseEntity } from '@mt-framework-ng/core';
import { RectifyProblemDTO } from '../../rectify-issue/model/rectify-problem-dto';

/**
 * Generated By SmartSwagger DTO
 * @Author chenzhongde
 * @Date 2021/11/3
 */
export interface RectifyTimeLineDTO extends AbstractBaseEntity {
  /**
   * 内容
   */
  content?: string;

  /**
   * 对象ID
   */
  objectId?: string;

  /**
   * 对象类型
   */
  objectType?: string;

  /**
   * 关联所属问题对象
   */
  rectifyProblem?: RectifyProblemDTO;
}
