import { AbstractBaseEntity, SystemFileDTO } from '@mt-framework-ng/core';
import { UserDTO } from '@ng-mt-framework/api';
import { RectifyMeasureDTO } from '../../audit-post/model/RectifyMeasureDTO';

/**
 * Generated By SmartSwagger DTO
 * @Author chenzhongde
 * @Date 2021/11/4
 */
export interface RectifyMeasureReplyDTO extends AbstractBaseEntity {
  /**
   * 回复内容
   */
  replyContent?: string;

  /**
   * 阅读状态
   */
  readStatus?: boolean;

  /**
   * 首次阅读日期
   */
  readTime?: string;

  /**
   * 是否审计部门回复： true : 审计部  false : 整改部门
   */
  isAudit?: boolean;

  /**
   * 整改措施
   */
  rectifyMeasure?: RectifyMeasureDTO;

  /**
   * 关联文件
   */
  attachFiles?: Array<SystemFileDTO>;

  /**
   * 关联附件编码集合
   */
  attachFileIds?: Array<string>;

  /**
   * 措施交互数据接受人
   */
  handler?: UserDTO;

  /**
   * 消息接受人id
   */
  handlerId?: string;

  /**
   * 整改措施id
   */
  rectifyMeasureId?: string;
}
