import { AbstractBaseEntity, SystemFileDTO } from '@mt-framework-ng/core';
import { RectifyProblemDTO } from '../../rectify-issue/model/rectify-problem-dto';

/**
 * Generated By SmartSwagger DTO
 * @Author chenzhongde
 * @Date 2021/11/4
 */
export interface RectifyMeasureDTO extends AbstractBaseEntity {
  /**
   * 措施状态
   */
  measureStatus?: string;

  /**
   * 措施类型
   */
  measureType?: string;

  /**
   * 整改措施内容
   */
  measureContent?: string;

  /**
   * 整改拟完成时间
   */
  rectifyEndTime?: string;

  /**
   * 整改拟开始时间
   */
  rectifyStartTime?: string;

  /**
   * 整改进度
   */
  rectifyProgress?: number;

  /**
   * 关联文件
   */
  attachFiles?: Array<SystemFileDTO>;

  /**
   * 关联所属问题对象
   */
  rectifyProblem?: RectifyProblemDTO;

  /**
   * 未阅读信息数
   */
  notReadNum?: number;

  /**
   * 整改问题清单id
   */
  rectifyProblemId?: string;

  /**
   * 关联附件编码集合
   */
  attachFileIds?: Array<string>;
}
