import { AbstractBaseEntity } from '@mt-framework-ng/core';
import { RectifyProblemDTO } from '../../rectify-issue/model/rectify-problem-dto';

/**
 * Generated By SmartSwagger DTO
 * @Author chenzhongde
 * @Date 2021/11/3
 */
export interface RectifyEffectDTO extends AbstractBaseEntity {
  /**
   * 审计挽回金额(元)
   */
  auditRecoveryAmount?: number;

  /**
   * 上缴（追回）资金(元)
   */
  recoveredAmount?: number;

  /**
   * 财务处理资金(元)
   */
  financialTransactionAmount?: number;

  /**
   * 促进节约资金
   */
  promoteSavingsAmount?: number;

  /**
   * 整改提出管理建议(条)
   */
  managementProposalCount?: number;

  /**
   * 违纪违规金额(元)
   */
  violateDisciplinesAmount?: number;

  /**
   * 整改后完善的制度(条)
   */
  perfectRegulationCount?: number;

  /**
   * 整改效益提升(元)
   */
  efficiencyGainsAmount?: number;

  /**
   * 审计建议（条）
   */
  adviceCount?: number;

  /**
   * 审计意见（条）
   */
  auditOpinionCount?: number;

  /**
   * 状态
   */
  status?: string;

  /**
   * 关联所属问题对象
   */
  rectifyProblem?: RectifyProblemDTO;

  /**
   * 关联整改问题id
   */
  rectifyProblemId?: string;
}
