import { SystemFileDTO } from '@mt-framework-ng/core';

/**
 * Generated By SmartSwagger DTO
 * @Author chenzhongde
 * @Date 2021/10/13
 */
export interface RectifyMeasureEditInfoDTO {
  /**
   * 整改措施状态
   */
  measureStatus: string;

  /**
   * 整改措施进度
   */
  rectifyProgress?: number;

  /**
   * 对象ID，新增时应当为null, 系统会自动生成
   */
  id?: string;

  /**
   * 措施类型
   */
  measureType: string;

  /**
   * 整改措施内容
   */
  measureContent: string;

  /**
   * 整改拟完成时间
   */
  rectifyCompleteTime: string;

  /**
   * 整改措施回复
   */
  // rectifyMeasureReplys: Array<RectifyMeasureReplyDTO>;

  /**
   * 关联文件
   */
  systemFiles: Array<SystemFileDTO>;

  /**
   * 整改问题清单id
   */
  rectifyProblemId: string;
}
