import { AbstractBaseEntity, SystemFileDTO } from '@mt-framework-ng/core';
import { UserDTO } from '@ng-mt-framework/api';

/**
 * Generated By SmartSwagger DTO
 * @Author chenzhongde
 * @Date 2021/11/3
 */
export interface RectifyProblemDelayApplyDTO extends AbstractBaseEntity {
  /**
   * 状态
   */
  status?: string;

  /**
   * 申请原因
   */
  applyReason?: string;

  /**
   * 提交延期截至日期
   */
  delayEndTime?: string;

  /**
   * 批复日期
   */
  replyTime?: string;

  /**
   * 批复意见
   */
  replyComments?: string;

  /**
   * 申请原因
   */
  beforeRectifyEndTime?: string;

  /**
   * 申请批复人编码
   */
  replyUser?: UserDTO;

  /**
   * 关联附件编码集合
   */
  attachFiles?: Array<SystemFileDTO>;

  /**
   * 申请批复人编码
   */
  replyUserId?: string;

  /**
   * 关联附件编码集合
   */
  attachFileIds?: Array<string>;
}
