import { SystemFileDTO } from '@mt-framework-ng/core';
import { RoleDTO, UserBaseDTO, UserDTO } from '@ng-mt-framework/api';

/**
 * Generated By SmartSwagger DTO
 * @Author chenzhongde
 * @Date 2021/10/13
 */
export interface RectifyMeasureReplyEditInfoDTO {
  /**
   * 对象ID，新增时应当为null, 系统会自动生成
   */
  id?: string;

  /**
   * 回复内容
   */
  replyContent: string;

  /**
   * 整改措施id
   */
  rectifyMeasureId: string;
}
