export const APP_AUDIT_MANAGE_DATA = {
  app: {
    name: 'menu',
    description: 'Ng-zorro & Ng-alain admin panel front-end framework',
  },
  menu: [
    {
      text: '',
      i18n: '',
      group: true,
      hideInBreadcrumb: true,
      children: [
        {
          text: '首页',
          link: '/audit-management/dashboard',
          i18n: 'menu.dashboard',
          icon: 'anticon-dashboard',
        },
        {
          text: '审计计划',
          i18n: 'menu.plan',
          icon: 'anticon-schedule',
          acl: [
            'EIA_AUDIT_PLAN_RETRIEVE',
            'EIA_AUDIT_PLAN_CREATE',
            'EIA_AUDIT_PLAN_UPDATE',
            'EIA_AUDIT_PLAN_DELETE',
            'EIA_AUDIT_PLAN_SUBMIT',
            'EIA_AUDIT_PLAN_APPROVE',
            'EIA_AUDIT_PROJECT_RETRIEVE',
            'EIA_AUDIT_PROJECT_CREATE',
            'EIA_AUDIT_PROJECT_UPDATE',
            'EIA_AUDIT_PROJECT_DELETE',
            'EIA_AUDIT_PROJECT_START',
            'EIA_AUDIT_PROJECT_CANCEL',
            'EIA_AUDIT_PROJECT_SUBMIT',
            'EIA_AUDIT_PROJECT_APPROVE',
            'EIA_AUDIT_PROJECT_CLOSE',
            'EIA_AUDIT_PROJECT_ARCHIVE',
          ],
          children: [
            {
              text: '计划编制',
              i18n: 'menu.plan.make',
              link: '/audit-management/plan-make',
              acl: [
                'EIA_AUDIT_PLAN_RETRIEVE',
                'EIA_AUDIT_PLAN_CREATE',
                'EIA_AUDIT_PLAN_UPDATE',
                'EIA_AUDIT_PLAN_DELETE',
                'EIA_AUDIT_PLAN_SUBMIT',
                'EIA_AUDIT_PLAN_APPROVE',
                'EIA_AUDIT_PROJECT_RETRIEVE',
                'EIA_AUDIT_PROJECT_CREATE',
                'EIA_AUDIT_PROJECT_UPDATE',
                'EIA_AUDIT_PROJECT_DELETE',
                'EIA_AUDIT_PROJECT_START',
                'EIA_AUDIT_PROJECT_CANCEL',
                'EIA_AUDIT_PROJECT_SUBMIT',
                'EIA_AUDIT_PROJECT_APPROVE',
                'EIA_AUDIT_PROJECT_CLOSE',
                'EIA_AUDIT_PROJECT_ARCHIVE',
              ],
            },
            {
              text: '计划调整',
              i18n: 'menu.plan.adjust',
              link: '/audit-management/plan-rectification',
              acl: [
                'EIA_AUDIT_PLAN_RETRIEVE',
                'EIA_AUDIT_PLAN_CREATE',
                'EIA_AUDIT_PLAN_UPDATE',
                'EIA_AUDIT_PLAN_DELETE',
                'EIA_AUDIT_PLAN_SUBMIT',
                'EIA_AUDIT_PLAN_APPROVE',
                'EIA_AUDIT_PROJECT_RETRIEVE',
                'EIA_AUDIT_PROJECT_CREATE',
                'EIA_AUDIT_PROJECT_UPDATE',
                'EIA_AUDIT_PROJECT_DELETE',
                'EIA_AUDIT_PROJECT_START',
                'EIA_AUDIT_PROJECT_CANCEL',
                'EIA_AUDIT_PROJECT_SUBMIT',
                'EIA_AUDIT_PROJECT_APPROVE',
                'EIA_AUDIT_PROJECT_CLOSE',
                'EIA_AUDIT_PROJECT_ARCHIVE',
              ],
            },
            {
              text: '计划审批',
              i18n: 'menu.plan.approve',
              link: '/audit-management/plan-approve',
              acl: [
                'EIA_AUDIT_PLAN_RETRIEVE',
                'EIA_AUDIT_PLAN_CREATE',
                'EIA_AUDIT_PLAN_UPDATE',
                'EIA_AUDIT_PLAN_DELETE',
                'EIA_AUDIT_PLAN_SUBMIT',
                'EIA_AUDIT_PLAN_APPROVE',
                'EIA_AUDIT_PROJECT_RETRIEVE',
                'EIA_AUDIT_PROJECT_CREATE',
                'EIA_AUDIT_PROJECT_UPDATE',
                'EIA_AUDIT_PROJECT_DELETE',
                'EIA_AUDIT_PROJECT_START',
                'EIA_AUDIT_PROJECT_CANCEL',
                'EIA_AUDIT_PROJECT_SUBMIT',
                'EIA_AUDIT_PROJECT_APPROVE',
                'EIA_AUDIT_PROJECT_CLOSE',
                'EIA_AUDIT_PROJECT_ARCHIVE',
              ],
            },
          ],
        },
        {
          text: '审计标准',
          i18n: 'menu.standard',
          icon: 'anticon-compass',
          children: [
            {
              text: '审计方案',
              i18n: 'menu.standard.type',
              link: '/audit-management/type',
              acl: [
                'EIA_STANDARD_AUDIT_TYPE_CREATE',
                'EIA_STANDARD_AUDIT_TYPE_UPDATE',
                'EIA_STANDARD_AUDIT_TYPE_DELETE',
                'EIA_STANDARD_AUDIT_TYPE_RETRIEVE',
              ],
            },
            {
              text: '审计事项',
              i18n: 'menu.standard.matter',
              link: '/audit-management/matter',
              acl: [
                'EIA_STANDARD_AUDIT_MATTERS_CREATE',
                'EIA_STANDARD_AUDIT_MATTERS_UPDATE',
                'EIA_STANDARD_AUDIT_MATTERS_DELETE',
                'EIA_STANDARD_AUDIT_MATTERS_RETRIEVE',
              ],
            },
            {
              text: '文书模板',
              i18n: 'menu.standard.template',
              link: '/insight/special-report/template-info',
            },
            {
              text: '抽样规则库',
              i18n: 'menu.standard.sampling',
              link: '/audit-management/sampling',
            },
          ],
        },
        {
          text: '审计知识库',
          i18n: 'menu.material',
          icon: 'anticon-book',
          children: [
            {
              text: '国家法律法规',
              i18n: 'menu.material.law',
              link: '/audit-management/national-laws-regulations',
              acl: [
                'EIA_KNOW_LEDGE_LAW_CREATE',
                'EIA_KNOW_LEDGE_LAW_UPDATE',
                'EIA_KNOW_LEDGE_LAW_DELETE',
                'EIA_KNOW_LEDGE_LAW_RETRIEVE',
              ],
            },
            {
              text: '企业规章制度',
              i18n: 'menu.material.rule',
              link: '/audit-management/national-laws-regulations/enterprise-regulation-institution',
              acl: [
                'EIA_KNOW_LEDGE_BUSINESS_RULE_CREATE',
                'EIA_KNOW_LEDGE_BUSINESS_RULE_UPDATE',
                'EIA_KNOW_LEDGE_BUSINESS_RULE_DELETE',
                'EIA_KNOW_LEDGE_BUSINESS_RULE_RETRIEVE',
              ],
            },
            {
              text: '经验案例',
              i18n: 'menu.material.case',
              link: '/audit-management/national-laws-regulations/example-case',
              acl: [
                'EIA_KNOW_LEDGE_CASE_CREATE',
                'EIA_KNOW_LEDGE_CASE_UPDATE',
                'EIA_KNOW_LEDGE_CASE_DELETE',
                'EIA_KNOW_LEDGE_CASE_RETRIEVE',
              ],
            },
          ],
        },
        {
          text: '审计资源',
          i18n: 'menu.resource',
          icon: 'anticon-database',
          children: [
            {
              text: '审计对象管理',
              i18n: 'menu.resource.object',
              link: '/audit-management/auditee',
              acl: [
                'EIA_RESOURCE_AUDITEE_CREATE',
                'EIA_RESOURCE_AUDITEE_UPDATE',
                'EIA_RESOURCE_AUDITEE_DELETE',
                'EIA_RESOURCE_AUDITEE_RETRIEVE',
              ],
              children: [
                {
                  text: '被审计人员',
                  i18n: 'menu.resource.object.auditedMember',
                  link: '/audit-management/auditee/auditedMember',
                },
                {
                  text: '被审计单位',
                  i18n: 'menu.resource.object.auditee',
                  link: '/audit-management/auditee',
                },
              ],
            },
            {
              text: '审计人员',
              i18n: 'menu.resource.person',
              link: '/audit-management/auditor',
              acl: ['EIA_AUDITOR_CREATE', 'EIA_AUDITOR_UPDATE', 'EIA_AUDITOR_DELETE', 'EIA_AUDITOR_RETRIEVE'],
            },
            {
              text: '风险地图',
              i18n: 'menu.risk.map',
              link: '/audit-management/risk-map',
            },
          ],
        },
        {
          text: '人员绩效考核',
          icon: 'anticon-exception',
          i18n: 'menu.appraisal',
          link: '/audit-management/performance-appraisal',
        },
        {
          text: '周报管理',
          icon: 'anticon-book',
          i18n: 'menu.weekly',
          link: '/audit-management/weekly-management',
        },
      ],
    },
  ],
};
